spring.application.name=MovieUserService
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration

spring.security.user.name=dhanush
spring.security.user.password=12345678

jwt.public-key=${JWT_PUBLIC_KEY}
jwt.private-key=${JWT_PRIVATE_KEY}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
app.frontend.url=${APP_FRONTEND_URL}

spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.username=${SPRING_DATA_REDIS_USERNAME}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}

spring.devtools.restart.enabled=true

user-client.base-url=${USER_CLIENT_BASE_URL}

management.endpoints.web.exposure.include=health,info
management.info.env.enabled=false

info.app.name=Movie Service
info.app.version=1.0
info.app.author=