CREATE TABLE movies (
    id INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    year INTEGER,
    genre VARCHAR(255) NOT NULL,
    rating NUMERIC(3, 1),
    votes INTEGER,
    director VARCHAR(255),
    actor_1 VARCHAR(255),
    actor_2 VARCHAR(255),
    duration_min INTEGER,
    budget_million NUMERIC(10, 1),
    revenue_million NUMERIC(10, 1)
);

CREATE TABLE users (
    user_id UUID PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    username VARCHAR(255) UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    age INTEGER NOT NULL,
    mobile VARCHAR(255) UNIQUE,
    gender VARCHAR(255),
    provider VARCHAR(255) NOT NULL,
    is_profile_completed BOOLEAN,
    is_email_verified BOOLEAN
);

CREATE TABLE user_roles (
    user_id UUID NOT NULL,
    role VARCHAR(255),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);

CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255),
    author_user_id UUID,
    CONSTRAINT fk_posts_author FOREIGN KEY (author_user_id) REFERENCES users (user_id)
);

CREATE TABLE user_session (
    id UUID PRIMARY KEY,
    user_id UUID,
    refresh_token VARCHAR(255),
    browser VARCHAR(255),
    os VARCHAR(255),
    device_type VARCHAR(255),
    ip_address VARCHAR(255),
    login_time TIMESTAMP(6),
    expires_at TIMESTAMP(6),
    revoked BOOLEAN,
    CONSTRAINT fk_user_session_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);